server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # API requests -> Spring Boot backend
    location /api/ {
        proxy_pass http://backend:8080/api/;

        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Prevent Spring Boot CORS from rejecting the random
        # Minikube localhost/127.0.0.1 origin.
        proxy_set_header Origin "";

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # React Router support
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Static assets
    location /assets/ {
        try_files $uri =404;
        access_log off;
        expires 7d;
    }

    # Security headers
    add_header X-Content-Type-Options "nosniff";
    add_header X-Frame-Options "SAMEORIGIN";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
}