import { useEffect, useState } from 'react'
import { getCalendar } from '../services/calendarService'
import { PageHeader, Card, StatusBadge } from '../components/UI'
import { holidays2026 } from '../data/holidays2026'

export default function Calendar() {
  const [year, setYear] = useState(new Date().getFullYear()); const [data, setData] = useState({ leaves: [] }); const [error, setError] = useState('')
  useEffect(() => { getCalendar(year).then(setData).catch(() => setError('Unable to load your calendar.')) }, [year])
  const leaveFor = (date) => data.leaves.find((leave) => date >= leave.startDate && date <= leave.endDate)
  const holidayFor = (date) => year === 2026 ? holidays2026.find((holiday) => holiday.date === date) : null
  const formatDate = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`
  const months = Array.from({ length: 12 }, (_, month) => new Date(year, month, 1))
  const nationalHolidays = holidays2026.filter((holiday) => holiday.category === 'National holiday')
  const festivalHolidays = holidays2026.filter((holiday) => holiday.category !== 'National holiday')
  return <><PageHeader eyebrow="Workspace / Calendar" title={`${year} leave calendar`} description="See your leave, national holidays, and festivals across the year." action={<div className="form-row"><button onClick={() => setYear(year - 1)}>Previous</button><button onClick={() => setYear(new Date().getFullYear())}>Current year</button><button onClick={() => setYear(year + 1)}>Next</button></div>} />{error && <div className="alert error">{error}</div>}<div className="calendar-grid">{months.map((month) => { const start = new Date(year, month.getMonth(), 1); const days = new Date(year, month.getMonth() + 1, 0).getDate(); const offset = (start.getDay() + 6) % 7; return <Card key={month.getMonth()}><h3>{month.toLocaleString('default', { month: 'long' })}</h3><div className="calendar-week">{['M','T','W','T','F','S','S'].map((day, index) => <span key={`${day}-${index}`}>{day}</span>)}{Array.from({ length: offset }, (_, index) => <i key={`empty-${index}`} />)}{Array.from({ length: days }, (_, index) => { const date = new Date(year, month.getMonth(), index + 1); const iso = formatDate(date); const leave = leaveFor(iso); const holiday = holidayFor(iso); return <span key={iso} className={`${date.getDay() === 0 || date.getDay() === 6 ? 'weekend' : ''} ${leave ? `leave-${leave.status.toLowerCase()}` : ''} ${holiday ? 'holiday' : ''}`} title={[iso, holiday?.name, leave && `${leave.status}: ${leave.reason}`].filter(Boolean).join(' - ')}>{index + 1}</span> })}</div></Card> })}</div><div className="calendar-legend"><span>Approved</span><span>Pending</span><span>Rejected</span><span>Weekend</span><span>Holiday</span></div>{year === 2026 && <div className="holiday-sections"><Card><h2>Major National Holidays 2026</h2>{nationalHolidays.map((holiday) => <p key={holiday.date}><strong>{holiday.date}</strong> {holiday.name}</p>)}</Card><Card><h2>Key Festivals &amp; Public Holidays 2026</h2>{festivalHolidays.map((holiday) => <p key={holiday.date}><strong>{holiday.date}</strong> {holiday.name}{holiday.tentative ? ' (date may vary)' : ''}</p>)}</Card></div>}<div>{data.leaves.map((leave) => <p key={leave.id}><StatusBadge status={leave.status} /> {leave.startDate} to {leave.endDate} ({leave.numberOfDays} working days)</p>)}</div></>
}