import { useState } from 'react'
import { Link, Navigate, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'
import { Button, Field } from '../components/UI'

export default function Login() {
  const { login, user, isAuthenticated } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [form, setForm] = useState({ email: '', password: '' }); const [show, setShow] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  if (isAuthenticated) return <Navigate to={user?.role === 'ADMIN' ? '/admin/dashboard' : '/dashboard'} replace />
  const submit = async (event) => { event.preventDefault(); if (!form.email || !form.password) return setError('Enter your email and password to continue.'); setLoading(true); setError(''); try { const nextUser = await login(form); navigate(nextUser.role === 'ADMIN' ? '/admin/dashboard' : (location.state?.from?.pathname || '/dashboard')) } catch (error) { setError(error.response?.data?.message || error.message || 'Unable to sign in.') } finally { setLoading(false) } }
  return <div className="auth-page"><div className="auth-aside"><div className="brand light"><span className="brand-mark">L</span><span>leave<span>web</span></span></div><div className="auth-quote"><span className="eyebrow">People operations, simplified</span><h1>Time away should feel effortless.</h1><p>Give your team a clearer way to plan, request, and manage leave.</p><div className="quote-footer"><span className="avatar">MA</span><span>“Finally, a leave tool that feels human.”<small>Elena Park, People Ops</small></span></div></div><div className="auth-decoration">LW / 26</div></div><main className="auth-main"><div className="auth-form-wrap"><span className="eyebrow">Welcome back</span><h2>Sign in to LeaveWeb</h2><p className="auth-subtitle">Your calm, clear workspace for time off.</p><form onSubmit={submit} noValidate><Field label="Work email or username" type="email" placeholder="you@company.com" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><label className="field"><span>Password</span><div className="password-wrap"><input type={show ? 'text' : 'password'} placeholder="Enter your password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><button type="button" onClick={() => setShow(!show)}>{show ? 'Hide' : 'Show'}</button></div></label>{error && <div className="alert error">{error}</div>}<div className="form-row"><label className="check"><input type="checkbox" /> Remember me</label><a href="#forgot">Forgot password?</a></div><Button type="submit" className="full-width">{loading ? 'Signing in...' : 'Sign in'} <span>→</span></Button></form><p className="switch-auth">New to LeaveWeb? <Link to="/register">Create an account</Link></p></div></main></div>
}