import { BrowserRouter, Navigate, Route, Routes } from 'react-router-dom'
import { AuthProvider } from './context/AuthContext'
import { NotificationProvider } from './context/NotificationContext'
import AppLayout from './layouts/AppLayout'
import { AdminRoute, ProtectedRoute } from './layouts/ProtectedRoute'
import Login from './pages/Login'
import Register from './pages/Register'
import Dashboard from './pages/Dashboard'
import ApplyLeave from './pages/ApplyLeave'
import MyLeaves from './pages/MyLeaves'
import LeaveDetails from './pages/LeaveDetails'
import Profile from './pages/Profile'
import Notifications from './pages/Notifications'
import AdminDashboard from './pages/admin/AdminDashboard'
import ManageUsers from './pages/admin/ManageUsers'
import ManageLeaves from './pages/admin/ManageLeaves'
import LeaveTypes from './pages/admin/LeaveTypes'
import Reports from './pages/admin/Reports'
import Calendar from './pages/Calendar'

export default function App() { return <BrowserRouter><AuthProvider><NotificationProvider><Routes><Route path="/login" element={<Login />} /><Route path="/register" element={<Register />} /><Route element={<ProtectedRoute />}><Route element={<AppLayout />}><Route path="/dashboard" element={<Dashboard />} /><Route path="/apply-leave" element={<ApplyLeave />} /><Route path="/my-leaves" element={<MyLeaves />} /><Route path="/calendar" element={<Calendar />} /><Route path="/leaves/:id" element={<LeaveDetails />} /><Route path="/profile" element={<Profile />} /><Route path="/notifications" element={<Notifications />} /><Route element={<AdminRoute />}><Route path="/admin" element={<Navigate to="/admin/dashboard" replace />} /><Route path="/admin/dashboard" element={<AdminDashboard />} /><Route path="/admin/users" element={<ManageUsers />} /><Route path="/admin/leaves" element={<ManageLeaves />} /><Route path="/admin/leave-types" element={<LeaveTypes />} /><Route path="/admin/reports" element={<Reports />} /></Route></Route></Route><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></NotificationProvider></AuthProvider></BrowserRouter> }